import { Helmet } from "react-helmet";

export default function PrivacyPolicy() {

  return (
    <>
      <Helmet>
        <title>Basket Rush | Privacy Policy</title>
      </Helmet>
      <div className="">
      <h1>Privacy Policy</h1>
      <p>Last updated: March 31, 2025</p>
      <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>

      <h2>Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.</p>

      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
        <li><strong>Application</strong> refers to Basket Rush, the software program provided by the Company.</li>
        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Afzal (developer of Basket Rush).</li>
        <li><strong>Country</strong> refers to: Nepal</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Application.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>

      <h2>Collecting and Using Your Personal Data</h2>
      <p>Basket Rush does not collect any personal data. All data related to your game progress and in-app activities are saved locally on your device and are under your control. The data is not transferred to the Company or any third parties.</p>

      <h2>Security of Your Personal Data</h2>
      <p>The security of Your Personal Data is important to Us. Once the Application is deleted, the data will no longer be available on your Device. You can also update or delete the data yourself within the Application at any time.</p>

      <h2>Children's Privacy</h2>
      <p>Since no data is transmitted off the device, Basket Rush ensures that Children's Privacy is protected. The Application is suitable for all ages and complies with regulations protecting children's privacy.</p>

      <h2>Changes to this Privacy Policy</h2>
      <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

      <h2>Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul>
        <li>By email: <a href="mailto:dev.afzalansari@gmail.com">dev.afzalansari@gmail.com</a></li>
      </ul>
      </div>
    </>
  )
}
